name: Node.js CI

on:
  pull_request:
    branches: [ master ]

jobs:      
  build:
    runs-on: ubuntu-latest
    needs: create-envfile
    steps:
    - uses: actions/checkout@v3
    - uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_FIREBASE_SERVICE_ACCOUNT_BASE64: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}
        envkey_MIXPANEL_PROJECT_TOKEN: ${{ secrets.MIXPANEL_PROJECT_TOKEN }}
        file_name: .env
        fail_on_empty: false 
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'    
    - run: ls -a
    - run: npm ci
    - run: make test
