name: Node.js CI

on:
  pull_request:
    branches: [ master ]

jobs:
  create-envfile:
      runs-on: ubuntu-latest
      steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_FIREBASE_SERVICE_ACCOUNT_BASE64: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}
          envkey_MIXPANEL_PROJECT_TOKEN: ${{ secrets.MIXPANEL_PROJECT_TOKEN }}
          directory: ./sadaqah-v2
          file_name: .env
          fail_on_empty: false
  build:
    runs-on: ubuntu-latest
    needs: create-envfile
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: ls -a
    - run: npm ci
    - run: make test
